-- MySQL Script generated by MySQL Workbench
-- Mon Feb 11 15:36:33 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gpqs
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gpqs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gpqs` DEFAULT CHARACTER SET utf8 ;
USE `gpqs` ;

-- -----------------------------------------------------
-- Table `gpqs`.`User_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpqs`.`User_role` (
  `urol_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `urol_name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`urol_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gpqs`.`Company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpqs`.`Company` (
  `com_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `com_name` VARCHAR(500) NOT NULL,
  `com_description` VARCHAR(1000) NULL,
  PRIMARY KEY (`com_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gpqs`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpqs`.`User` (
  `usr_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `usr_username` VARCHAR(45) NOT NULL,
  `usr_user_role_id` INT UNSIGNED NOT NULL,
  `usr_company_id` INT UNSIGNED NULL,
  `usr_created_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`usr_id`),
  UNIQUE INDEX `user_name_UNIQUE` (`usr_username` ASC),
  INDEX `user_fk_id_user_role_idx` (`usr_user_role_id` ASC),
  INDEX `user_fk_id_company_idx` (`usr_company_id` ASC),
  CONSTRAINT `user_fk_urol_id`
    FOREIGN KEY (`usr_user_role_id`)
    REFERENCES `gpqs`.`User_role` (`urol_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `user_fk_com_id`
    FOREIGN KEY (`usr_company_id`)
    REFERENCES `gpqs`.`Company` (`com_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gpqs`.`Queue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpqs`.`Queue` (
  `que_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `que_company_id` INT UNSIGNED NOT NULL,
  `que_name` VARCHAR(500) NOT NULL,
  `que_description` VARCHAR(1000) NULL,
  `que_start_time` TIMESTAMP NULL,
  `que_end_time` TIMESTAMP NULL,
  `que_created_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`que_id`),
  INDEX `queue_fk_com_id_idx` (`que_company_id` ASC),
  CONSTRAINT `queue_fk_com_id`
    FOREIGN KEY (`que_company_id`)
    REFERENCES `gpqs`.`Company` (`com_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gpqs`.`Moderator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpqs`.`Moderator` (
  `mod_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `mod_name` VARCHAR(500) NOT NULL,
  `mod_email` VARCHAR(100) NOT NULL,
  `mod_company_id` INT UNSIGNED NULL,
  `mod_created_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`mod_id`),
  INDEX `moderator_fk_comp_id_idx` (`mod_company_id` ASC),
  CONSTRAINT `moderator_fk_com_id`
    FOREIGN KEY (`mod_company_id`)
    REFERENCES `gpqs`.`Company` (`com_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gpqs`.`Queue_Moderator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpqs`.`Queue_Moderator` (
  `qmod_queue_id` INT UNSIGNED NOT NULL,
  `qmod_moderator_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`qmod_queue_id`, `qmod_moderator_id`),
  INDEX `queue_moderator_fk_mod_id_idx` (`qmod_moderator_id` ASC),
  CONSTRAINT `queue_moderator_fk_que_id`
    FOREIGN KEY (`qmod_queue_id`)
    REFERENCES `gpqs`.`Queue` (`que_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `queue_moderator_fk_mod_id`
    FOREIGN KEY (`qmod_moderator_id`)
    REFERENCES `gpqs`.`Moderator` (`mod_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
